name: Update Kubernetes

on:
  workflow_run:
    workflows: ["CD"]
    types:
      - completed
    branches:
      - main

jobs:
  update-manifest:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get commit SHA
        id: sha
        run: echo "short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Update Kubernetes manifest image tag
        run: |
          sed -i "s|image: khdevops/etl-app:.*|image: khdevops/etl-app:${{ steps.sha.outputs.short }}|" kubernetes/platform/base/elt-cronjob.yaml

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'kubernetes/platform/base/elt-cronjob.yaml'
          message: 'chore: update image to ${{ steps.sha.outputs.short }}'
          new_branch: 'update-image-${{ steps.sha.outputs.short }}'
          push: '--force origin update-image-${{ steps.sha.outputs.short }}'

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-image-${{ steps.sha.outputs.short }}
          title: 'Update image to ${{ steps.sha.outputs.short }}'
          body: 'Auto-update image version after successful CD build'
          base: main

      - name: Enable auto-merge
        if: steps.create-pr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: squash
